package com.example.spaceshooter.constant;


public interface GameConstant {

	int LIFEAMOUNT = 5;
	int MISSILECOUNT = 5;
	int LIFE_MAXCOUNT = 9;
	int MISSILE_MAXCOUNT = 9;
	int GAMESPEED = 1;
	int MAXGRADE = 6;
	int LEVELUP_SCORE = 50000;


	int SMALLPLANE_COUNT = 10;
	int MIDDLEPLANE_COUNT = 8;
	int BIGPLANE_COUNT = 10;
	int BOSSPLANE_COUNT = 1;

	int SMALLPLANE_BLOOD = 1;
	int MIDDLEPLANE_BLOOD = 40;
	int BIGPLANE_BLOOD = 120;
	int BOSSPLANE_BLOOD = 1000;
	int BOSSPLANE_ANGER_BLOOD = 700;
	int BOSSPLANE_CRAZY_BLOOD = 500;
	int BOSSPLANE_LIMIT_BLOOD = 150;

	int SMALLPLANE_SCORE = 100;
	int MIDDLEPLANE_SCORE = 300;
	int BIGPLANE_SCORE = 800;
	int BOSSPLANE_SCORE = 2000;

	int MIDDLEPLANE_APPEARSCORE = 2000;
	int BIGPLANE_APPEARSCORE = 8000;
	int BOSSPLANE_APPEARSCORE = 30000;
	int MISSILE_APPEARSCORE = 5000;
	int LIFE_APPEARSCORE = 10000;
	int BULLET1_APPEARSCORE = 3000;
	int BULLET2_APPEARSCORE = 7000;

	int MISSILE_HARM = 80;
	int MYBULLET_HARM = 1;
	int MYBULLET1_HARM = 4;
	int MYBULLET2_HARM = 5;

	int MYBULLET_SPEED = 80;
	int MYBULLET1_SPEED = 100;
	int MYBULLET2_SPEED = 120;
	int MYPLANE_SPEED = 30;
	
	int BIGPLANE_SPEED = 3;
	
	
	long BOOM_TIME = 2000;
	long INVINCIBLE_TIME = 5000;
	long MISSILEBOOM_TIME = 500;
	long MYSPECIALBULLET_DURATION = 15000;

}
